export const DEMO_ACTION = "DEMO/DEMO_ACTION";

export const DEMO_SAGA_ACTION = "DEMO/DEMO_SAGA_ACTION";
export const DEMO_SAGA_ASYNC_ACTION = "DEMO/DEMO_SAGA_ASYNC_ACTION";

export const DEMO_ROUTE_ACTION = "DEMO/DEMO_ROUTE_ACTION";
